Algoritmo "problema_crescente"

Var
   x, y :inteiro


Inicio

     escreval("Digite dois numeros: ")
     leia(X)
     leia(y)
     


     enquanto x <> y  faca
     se x > y entao
       escreval("CRESCENTE!")
     senao
       escreval("DECRESCENTE!")
     fimse

       escreval("Digite outros dois numeros: ")
        leia(x)
        leia(y)

     fimenquanto
     
Fimalgoritmo